space fixes camera and new setting that changes camera behaviour
twohoursonelife/OneLife pull request #64
Opened 2021-06-24 01:03 UTC by Defalt36

2021-06-27 20:16 UTC, risvh commented
may wanna include centerCamera.ini in the setting folder

2021-06-27 20:21 UTC, Defalt36 commented
Maybe in the future when I change the layout of the settings page I put the missing settings there, but I don't see a reason to.

2021-06-27 20:25 UTC, risvh commented
Setting page doesn't include all the configurable settings, those omitted settings are configured with those ini files. Having the file there tells users what can be configured. If you place a setting in the code, better have it also in the setting folder for users' convenience.

2021-06-28 04:39 UTC, connorhsm requested changes
Otherwise looks good to me.

2021-06-28 04:39 UTC, connorhsm commented on gameSource/LivingLifePage.cpp
> +        if( vogMode || SettingsManager::getIntSetting( "centerCamera", 0 ) ) {
As indicated by @risvh , please do commit this settings file.

2021-06-28 09:33 UTC, connorhsm approved these changes

2021-06-28 09:34 UTC, merged