Infertility redo
twohoursonelife/OneLife pull request #9
Opened 2020-08-24 22:08 UTC by risvh

Players can now say phrases to declare themselves fertile or infertile
The fertility state is reflected in player names.

2020-08-29 01:53 UTC, connorhsm requested changes
Is there something that happens in the client when the phrase is recognised by the server?

For example, when you curse a player your speach turns purple and you hear a 'ding'. Could this be replicated?

2020-08-29 23:00 UTC, risvh commented
The name of the player will be changed to reflect the infertility state (EVE MOON -> EVE MOON +INFERTILE+), do you want something on top of this?

2020-08-30 14:09 UTC, connorhsm commented
Yes please, as described above. Just to make it absolutely clear that *something* occured.

2020-09-03 13:03 UTC, connorhsm approved these changes

2020-09-03 13:03 UTC, merged